# CodeRabbit AI Code Review Configuration
# Documentation: https://docs.coderabbit.ai/

language: "en-US"

reviews:
  high_level_summary: true
  review_status: true
  poem: true

  auto_review:
    enabled: true
    drafts: false

  path_filters:
    - "src/**/*"
    - "*.json"
    - "*.md"
    - ".github/**/*"
    - "!node_modules/**/*"
    - "!dist/**/*"
    - "!.astro/**/*"
    - "!pnpm-lock.yaml"

  path_instructions:
    - path: "src/data/**/*.ts"
      instructions: |
        This file contains medical calculation logic. Verify:
        - All calculations match established medical formulas and guidelines
        - Input validation with physiological limits (HR 40-220, BP 40-300, SpO2 0-100, etc.)
        - Division-by-zero guards and null safety for medical data
        - Error handling that never crashes medical calculations
        - Proper medical citations in file headers

    - path: "src/components/**/*.svelte"
      instructions: |
        This is a Svelte 5 medical calculator component. Verify:
        - Uses $state/$derived runes (NOT legacy let/reactive)
        - Touch targets minimum 60px for emergency gloved-hand use (py-5 or min-h-[60px])
        - ARIA labels on interactive elements + aria-live regions for dynamic results
        - Theme-aware styling with dark: variant pairs (no hardcoded light-only colors)
        - Error boundaries wrapping all calculations
        - Medical safety disclaimer present

    - path: "src/pages/**/*.astro"
      instructions: |
        This is an Astro page for a medical tool. Verify:
        - Light/dark mode colors use Tailwind variant pairs (bg-red-100 dark:bg-red-900/30)
        - No dark-only colors without light-mode counterparts
        - Single h1 per page (component should use h2+)
        - Medical disclaimer present for clinical tools
        - Component loaded with client:load

    - path: "public/sw.ts"
      instructions: |
        Service worker for PWA offline support. Verify:
        - All calculator pages are in ESSENTIAL_FILES and PRECACHE_URLS
        - APP_VERSION matches package.json, manifest.json, and version.ts
        - Cache names include version for proper invalidation

chat:
  auto_reply: true

tone_instructions: |
  Please provide constructive, professional feedback focused on:
  - Medical safety and accuracy (highest priority)
  - Code quality and maintainability
  - Emergency use context and accessibility
  - Performance for critical situations

  Be thorough but practical. This is a medical emergency application where
  reliability and speed are essential for patient safety.